### ISSUE TITLE
Nice work, but won't compile

### ISSUE THREAD

**Issue by chrwh** [wizche/m5paper-weather#1]
Hi,

Nice work, but it does not compile. I get the below error.

Best regards,
Christian

Compiling .pio\build\m5stack-fire\libc21\M5EPD\Fonts\Font16.c.o
In file included from src/Data.h:24:0,
                 from src/main.cpp:26:
src/Weather.h: In member function 'bool Weather::GetOpenWeatherJsonDoc(ArduinoJson6185_91::DynamicJsonDocument&)':
src/Weather.h:74:39: error: 'LATITUDE' was not declared in this scope
       uri += "?lat=" + String((float) LATITUDE, 5);
                                       ^
src/Weather.h:75:39: error: 'LONGITUDE' was not declared in this scope
       uri += "&lon=" + String((float) LONGITUDE, 5);
                                       ^
src/Weather.h:77:35: error: 'OPENWEATHER_API' was not declared in this scope
       uri += "&appid=" + (String) OPENWEATHER_API;
                                   ^
src/Weather.h:79:62: error: 'OPENWEATHER_SRV' was not declared in this scope
       Serial.printf("Requesting %s to %s:%d\n", uri.c_str(), OPENWEATHER_SRV, OPENWEATHER_PORT);
                                                              ^
src/Weather.h:79:79: error: 'OPENWEATHER_PORT' was not declared in this scope
       Serial.printf("Requesting %s to %s:%d\n", uri.c_str(), OPENWEATHER_SRV, OPENWEATHER_PORT);
                                                                               ^
src/Weather.h: In member function 'bool Weather::Fill(const JsonObject&)':
src/Weather.h:124:78: warning: 'typename ArduinoJson6185_91::enable_if<ArduinoJson6185_91::is_same<T, char*>::value, const char*>::type ArduinoJson6185_91::MemberProxy<TParent, TStringRef>::as() const [with T = char*; TObject = ArduinoJson6185_91::ElementProxy<ArduinoJson6185_91::MemberProxy<ArduinoJson6185_91::ElementProxy<ArduinoJson6185_91::ArrayRef>, const char*> >; TStringRef = const char*; typename ArduinoJson6185_91::enable_if<ArduinoJson6185_91::is_same<T, char*>::value, const char*>::type = const char*]' is deprecated: Replace as<char*>() with as<const char*>() [-Wdeprecated-declarations]
             dailyMain[i]    = daily_list[i]["weather"][0]["main"].as<char *>();
                                                                              ^
In file included from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:9:0,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson.hpp:21,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson.h:9,
                 from src/Weather.h:25,
                 from src/Data.h:24,
                 from src/main.cpp:26:
.pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:79:7: note: declared here
       as() const {
       ^
In file included from src/Data.h:24:0,
                 from src/main.cpp:26:
src/Weather.h:125:78: warning: 'typename ArduinoJson6185_91::enable_if<ArduinoJson6185_91::is_same<T, char*>::value, const char*>::type ArduinoJson6185_91::MemberProxy<TParent, TStringRef>::as() const [with T = char*; TObject = ArduinoJson6185_91::ElementProxy<ArduinoJson6185_91::MemberProxy<ArduinoJson6185_91::ElementProxy<ArduinoJson6185_91::ArrayRef>, const char*> >; TStringRef = const char*; typename ArduinoJson6185_91::enable_if<ArduinoJson6185_91::is_same<T, char*>::value, const char*>::type = const char*]' is deprecated: Replace as<char*>() with as<const char*>() [-Wdeprecated-declarations]
             dailyIcon[i]    = daily_list[i]["weather"][0]["icon"].as<char *>();
                                                                              ^
In file included from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:9:0,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson.hpp:21,
                 from .pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson.h:9,
                 from src/Weather.h:25,
                 from src/Data.h:24,
                 from src/main.cpp:26:
.pio/libdeps/m5stack-fire/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:79:7: note: declared here
       as() const {
       ^
In file included from src/main.cpp:26:0:
src/Data.h: In member function 'void MyData::Dump()':
src/Data.h:64:51: error: 'LATITUDE' was not declared in this scope
       Serial.println("Latitude: "        + String(LATITUDE));
                                                   ^
src/Data.h:65:51: error: 'LONGITUDE' was not declared in this scope
       Serial.println("Longitude: "       + String(LONGITUDE));
                                                   ^
Compiling .pio\build\m5stack-fire\libc21\M5EPD\Fonts\Font32rle.c.o
Compiling .pio\build\m5stack-fire\libc21\M5EPD\Fonts\Font64rle.c.o
In file included from src/main.cpp:27:0:
src/Display.h: In member function 'void WeatherDisplay::DrawHead()':
src/Display.h:153:28: error: 'CITY_NAME' was not declared in this scope
    canvas.drawCentreString(CITY_NAME, maxX / 2, 10, 1);
                            ^
In file included from src/main.cpp:30:0:
src/EPDWifi.h: In function 'bool StartWiFi(int&)':
src/EPDWifi.h:36:19: error: 'WIFI_SSID' was not declared in this scope
    Serial.println(WIFI_SSID);
                   ^
src/EPDWifi.h:39:26: error: 'WIFI_PW' was not declared in this scope
    WiFi.begin(WIFI_SSID, WIFI_PW);
                          ^
In file included from src/main.cpp:31:0:
src/Moon.h: In function 'bool GetMoonValues(MyData&)':
src/Moon.h:31:17: error: 'LATITUDE' was not declared in this scope
    mr.calculate(LATITUDE, LONGITUDE, time);
                 ^
src/Moon.h:31:27: error: 'LONGITUDE' was not declared in this scope
    mr.calculate(LATITUDE, LONGITUDE, time);
                           ^
*** [.pio\build\m5stack-fire\src\main.cpp.o] Error 1

**Comment by wizche** [comment]
Thanks for reporting, you need to rename `ConfigTemplate.h` into `Config.h` and put your own information in there... I updated the Readme accordingly.
